package pedrapapeltesoura;

import javax.swing.JOptionPane;

public class Tela extends javax.swing.JFrame {

    public int pontosP;
    public int pontosM;
    public int ganhador = 0;

    public Tela() {
        initComponents();
        btnPlay.setEnabled(false);
        int pontosP = 0;
        int pontosM = 0;
        int ganhador = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlConteudo = new javax.swing.JPanel();
        chkPedra = new javax.swing.JCheckBox();
        chkPapel = new javax.swing.JCheckBox();
        chkTesoura = new javax.swing.JCheckBox();
        btnPlay = new javax.swing.JButton();
        lblJogador = new javax.swing.JLabel();
        lblComputador = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblPontosPlayer = new javax.swing.JLabel();
        lblPontosMaquina = new javax.swing.JLabel();
        pnlRodape = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PEDRA PAPEL TESOURA");

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(134, 134, 134))
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkPedra.setText("PEDRA");
        chkPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPedraActionPerformed(evt);
            }
        });

        chkPapel.setText("PAPEL");
        chkPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPapelActionPerformed(evt);
            }
        });

        chkTesoura.setText("TESOURA");
        chkTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTesouraActionPerformed(evt);
            }
        });

        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lblJogador.setText("JOGADOR");

        lblComputador.setText("COMPUTADOR");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConteudoLayout = new javax.swing.GroupLayout(pnlConteudo);
        pnlConteudo.setLayout(pnlConteudoLayout);
        pnlConteudoLayout.setHorizontalGroup(
            pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConteudoLayout.createSequentialGroup()
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConteudoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlConteudoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblPontosPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConteudoLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblComputador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConteudoLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblPontosMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addGroup(pnlConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlConteudoLayout.createSequentialGroup()
                        .addComponent(chkPedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)
                        .addComponent(chkPapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93)
                        .addComponent(chkTesoura))
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlConteudoLayout.setVerticalGroup(
            pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConteudoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPedra)
                    .addComponent(chkPapel)
                    .addComponent(chkTesoura))
                .addGap(18, 18, 18)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJogador)
                    .addComponent(lblComputador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPontosPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPontosMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("MSB");

        javax.swing.GroupLayout pnlRodapeLayout = new javax.swing.GroupLayout(pnlRodape);
        pnlRodape.setLayout(pnlRodapeLayout);
        pnlRodapeLayout.setHorizontalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        pnlRodapeLayout.setVerticalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRodapeLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void iniciar() {
        if (chkPedra.isSelected() || chkPapel.isSelected() || chkTesoura.isSelected()) {
            btnPlay.setEnabled(true);
        } else {
            btnPlay.setEnabled(false);
        }
        
    }
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        int numeroAleatorio;

        if (chkPedra.isSelected()) {
            numeroAleatorio = randInt(0, 2);
            if (numeroAleatorio == 0) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n PEDRA");
                JOptionPane.showMessageDialog(null, "Empate");
                chkPedra.setSelected(false);

            } else if (numeroAleatorio == 1) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n PAPEL");
                JOptionPane.showMessageDialog(null, "Perdeu");
               chkPedra.setSelected(false);
               ganhador = 1;
               atualizar();

            } else {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n TESOURA");
                JOptionPane.showMessageDialog(null, "Venceu");
                chkPedra.setSelected(false);
                ganhador = 1;
                atualizar();
            }

        }else if (chkPapel.isSelected()) {
            numeroAleatorio = randInt(0, 2);
            if (numeroAleatorio == 0) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n PEDRA");
                JOptionPane.showMessageDialog(null, "Venceu");
                chkPapel.setSelected(false);
                ganhador = 0;
                atualizar();

            } else if (numeroAleatorio == 1) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n PAPEL");
                JOptionPane.showMessageDialog(null, "Empate");
                chkPapel.setSelected(false);

            } else {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n TESOURA");
                JOptionPane.showMessageDialog(null, "Perdeu");
                chkPapel.setSelected(false);
                ganhador = 1;
                atualizar();

            }

        } if (chkTesoura.isSelected()) {
            numeroAleatorio = randInt(0, 2);
            if (numeroAleatorio == 0) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n PEDRA");
                JOptionPane.showMessageDialog(null, "Perdeu");
                ganhador = 1;
                atualizar();
                

            } else if (numeroAleatorio == 1) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n PAPEL");
                JOptionPane.showMessageDialog(null, "Venceu");
                ganhador = 0;
               atualizar();

            } else if (numeroAleatorio == 2) {
                JOptionPane.showMessageDialog(null, "A máquina escolheu:\n TESOURA");
                JOptionPane.showMessageDialog(null, "Empatou");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma opção!");

        }


    }//GEN-LAST:event_btnPlayActionPerformed
    public void atualizar() {
        if (ganhador == 1) {
            pontosM += 1;
            lblPontosMaquina.setText("" + pontosM);
        } else {
            pontosP += 1;
            lblPontosPlayer.setText("" + pontosP);
        }

    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed
    private void reset() {
        pontosP = 0;
        pontosM = 0;
        lblPontosPlayer.setText("0");
        lblPontosMaquina.setText("0");
        chkPedra.setSelected(false);
        chkPapel.setSelected(false);
        chkTesoura.setSelected(false);
    }
    private void chkPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPedraActionPerformed
        iniciar();
        chkPapel.setSelected(false);
        chkTesoura.setSelected(false);

    }//GEN-LAST:event_chkPedraActionPerformed

    private void chkTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTesouraActionPerformed
        iniciar();
        chkPapel.setSelected(false);
        chkPedra.setSelected(false);
    }//GEN-LAST:event_chkTesouraActionPerformed

    private void chkPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPapelActionPerformed
        iniciar();
        chkPedra.setSelected(false);
        chkTesoura.setSelected(false);

    }//GEN-LAST:event_chkPapelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, epnlCabecalho     }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    public static int randInt(int min, int max) {
        java.util.Random rand = new java.util.Random();
        int randomNum = rand.nextInt((max - min) + 1) + min;
        return randomNum;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkPapel;
    private javax.swing.JCheckBox chkPedra;
    private javax.swing.JCheckBox chkTesoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblComputador;
    private javax.swing.JLabel lblJogador;
    private javax.swing.JLabel lblPontosMaquina;
    private javax.swing.JLabel lblPontosPlayer;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlConteudo;
    private javax.swing.JPanel pnlRodape;
    // End of variables declaration//GEN-END:variables
}
