/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pesoplanetario;

import javax.swing.JOptionPane;

/**
 *
 * @author marce
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnTela = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        chkMercurio = new javax.swing.JCheckBox();
        chkVenus = new javax.swing.JCheckBox();
        chkMarte = new javax.swing.JCheckBox();
        chkJupter = new javax.swing.JCheckBox();
        chkSaturno = new javax.swing.JCheckBox();
        chkUrano = new javax.swing.JCheckBox();
        txtPeso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnCalcular1 = new javax.swing.JButton();
        chkMercurio1 = new javax.swing.JCheckBox();
        chkVenus1 = new javax.swing.JCheckBox();
        chkMarte1 = new javax.swing.JCheckBox();
        chkJupter1 = new javax.swing.JCheckBox();
        chkSaturno1 = new javax.swing.JCheckBox();
        chkUrano1 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        lblCabecalho = new javax.swing.JLabel();
        lblMarceloBoeira = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        chkMercurio.setText("Mercurio");
        chkMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMercurioActionPerformed(evt);
            }
        });

        chkVenus.setText("Venus");
        chkVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVenusActionPerformed(evt);
            }
        });

        chkMarte.setText("Marte");
        chkMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMarteActionPerformed(evt);
            }
        });

        chkJupter.setText("Jupter");
        chkJupter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJupterActionPerformed(evt);
            }
        });

        chkSaturno.setText("Saturno");
        chkSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSaturnoActionPerformed(evt);
            }
        });

        chkUrano.setText("Urano");
        chkUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUranoActionPerformed(evt);
            }
        });

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plnTelaLayout = new javax.swing.GroupLayout(plnTela);
        plnTela.setLayout(plnTelaLayout);
        plnTelaLayout.setHorizontalGroup(
            plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnTelaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plnTelaLayout.createSequentialGroup()
                        .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkMercurio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkJupter, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkVenus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkSaturno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkMarte, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(chkUrano, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plnTelaLayout.setVerticalGroup(
            plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnTelaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addGap(18, 18, 18)
                .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMercurio)
                    .addComponent(chkVenus)
                    .addComponent(chkMarte))
                .addGap(18, 18, 18)
                .addGroup(plnTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJupter)
                    .addComponent(chkSaturno)
                    .addComponent(chkUrano))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        btnCalcular1.setText("Calcular");
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        chkMercurio1.setText("Mercurio");
        chkMercurio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMercurio1ActionPerformed(evt);
            }
        });

        chkVenus1.setText("Venus");

        chkMarte1.setText("Marte");

        chkJupter1.setText("Jupter");

        chkSaturno1.setText("Saturno");

        chkUrano1.setText("Urano");

        jTextField2.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkMarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkVenus1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMercurio1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkJupter1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSaturno1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkUrano1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular1)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(97, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnCalcular1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkMercurio1)
                        .addGap(18, 18, 18)
                        .addComponent(chkVenus1)
                        .addGap(18, 18, 18)
                        .addComponent(chkMarte1)
                        .addGap(18, 18, 18)
                        .addComponent(chkJupter1)
                        .addGap(18, 18, 18)
                        .addComponent(chkSaturno1)
                        .addGap(18, 18, 18)
                        .addComponent(chkUrano1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCabecalho.setText("CALCULE SEU PESO EM OUTRO PLANETA");

        lblMarceloBoeira.setText("Marcelo Boeira");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plnTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMarceloBoeira)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblCabecalho)
                .addGap(18, 18, 18)
                .addComponent(plnTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMarceloBoeira))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMercurioActionPerformed
        chkVenus.setSelected(false);
        chkMarte.setSelected(false);
        chkJupter.setSelected(false);
        chkUrano.setSelected(false);
        chkSaturno.setSelected(false);

    }//GEN-LAST:event_chkMercurioActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (txtPeso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, digite o seu peso.", "Erro de entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double peso;
        try {
            String pesoTexto = txtPeso.getText().replace(',', '.');
            peso = Double.parseDouble(pesoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, digite um peso válido.", "Erro de entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!chkMercurio.isSelected() && !chkVenus.isSelected() && !chkMarte.isSelected() && !chkJupter.isSelected() && !chkSaturno.isSelected() && !chkUrano.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione pelo menos um planeta.", "Erro de seleção", JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean mercurio = (boolean) chkMercurio.isSelected();
        boolean venus = (boolean) chkVenus.isSelected();
        boolean marte = (boolean) chkMarte.isSelected();
        boolean jupter = (boolean) chkJupter.isSelected();
        boolean urano = (boolean) chkUrano.isSelected();
        boolean saturno = (boolean) chkSaturno.isSelected();
        double gravidade = 0;
        String planeta = "";
        try {
            if (mercurio) {
                gravidade = 0.37;
                planeta = "Mercurio";
            } else if (venus) {
                gravidade = 0.88;
                planeta = "Venus";
            } else if (marte) {
                gravidade = 0.38;
                planeta = "Marte";
            } else if (jupter) {
                gravidade = 2.64;
                planeta = "Júpter";
            } else if (saturno) {
                gravidade = 1.15;
                planeta = "Saturno";
            } else if (urano) {
                gravidade = 1.17;
                planeta = "Urano";
            }
            JOptionPane.showMessageDialog(null, "SEU PESO EM " + planeta + " É: " + peso * gravidade);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor, digite um peso válido.", "Erro de entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void chkMercurio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMercurio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMercurio1ActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void chkVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVenusActionPerformed
        chkMercurio.setSelected(false);
        chkMarte.setSelected(false);
        chkJupter.setSelected(false);
        chkUrano.setSelected(false);
        chkSaturno.setSelected(false);
    }//GEN-LAST:event_chkVenusActionPerformed

    private void chkMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMarteActionPerformed
        chkMercurio.setSelected(false);
        chkVenus.setSelected(false);
        chkJupter.setSelected(false);
        chkUrano.setSelected(false);
        chkSaturno.setSelected(false);
    }//GEN-LAST:event_chkMarteActionPerformed

    private void chkJupterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJupterActionPerformed
        chkMercurio.setSelected(false);
        chkVenus.setSelected(false);
        chkMarte.setSelected(false);
        chkUrano.setSelected(false);
        chkSaturno.setSelected(false);
    }//GEN-LAST:event_chkJupterActionPerformed

    private void chkSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSaturnoActionPerformed
        chkMercurio.setSelected(false);
        chkVenus.setSelected(false);
        chkMarte.setSelected(false);
        chkUrano.setSelected(false);
        chkJupter.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_chkSaturnoActionPerformed

    private void chkUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUranoActionPerformed
        chkMercurio.setSelected(false);
        chkVenus.setSelected(false);
        chkMarte.setSelected(false);
        chkJupter.setSelected(false);
        chkSaturno.setSelected(false);   // TODO add your handling code here:
    }//GEN-LAST:event_chkUranoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JCheckBox chkJupter;
    private javax.swing.JCheckBox chkJupter1;
    private javax.swing.JCheckBox chkMarte;
    private javax.swing.JCheckBox chkMarte1;
    private javax.swing.JCheckBox chkMercurio;
    private javax.swing.JCheckBox chkMercurio1;
    private javax.swing.JCheckBox chkSaturno;
    private javax.swing.JCheckBox chkSaturno1;
    private javax.swing.JCheckBox chkUrano;
    private javax.swing.JCheckBox chkUrano1;
    private javax.swing.JCheckBox chkVenus;
    private javax.swing.JCheckBox chkVenus1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblMarceloBoeira;
    private javax.swing.JPanel plnTela;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
